/* The following code was generated by JFlex 1.7.0 tweaked for IntelliJ platform */

package com.deprosun.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static com.intellij.psi.TokenType.BAD_CHARACTER; // Pre-defined bad character token.
import static com.intellij.psi.TokenType.WHITE_SPACE; // Pre-defined whitespace character token.
import static com.deprosun.psi.SimpleTypes.*; // Note that is the class which is specified as `elementTypeHolderClass`
// in bnf grammar file. This will contain all other tokens which we will use.


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Mapper.flex</tt>
 */
public class MapperLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [9, 6, 6]
   * Total runtime size is 3488 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[(ZZ_CMAP_Z[ch>>12]<<6)|((ch>>6)&0x3f)]<<6)|(ch&0x3f)];
  }

  /* The ZZ_CMAP_Z table has 272 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\1\1\10\2\1\3\4\2\1\4\1\5\1\6\4\2\1\7\6\2\1\10\1\11\361\2");

  /* The ZZ_CMAP_Y table has 640 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\27\2\1\3\1\2\1\4\3\2\1\5\5\2\1\6\1\2\1\6\1\2\1\6\1\2\1\6\1\2\1\6"+
    "\1\2\1\6\1\2\1\6\1\2\1\6\1\2\1\6\1\2\1\6\1\2\1\7\1\2\1\7\1\3\4\2\1\5\1\7\34"+
    "\2\1\3\1\7\4\2\1\10\1\2\1\7\2\2\1\11\2\2\1\7\1\4\2\2\1\11\146\2\1\3\12\2\1"+
    "\7\1\5\2\2\1\12\1\2\1\7\5\2\1\4\114\2\1\7\25\2\1\3\56\2\1\6\1\2\1\4\1\13\2"+
    "\2\1\7\3\2\1\4\5\2\1\7\1\2\1\7\5\2\1\7\1\2\1\5\1\4\6\2\1\3\15\2\1\7\67\2\1"+
    "\3\3\2\1\7\61\2\1\14\105\2\1\7\32\2");

  /* The ZZ_CMAP_A table has 832 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\5\7\22\0\1\7\7\0\1\43\1\44\2\0\1\46\1\0\1\45\1\0\12\2\3\0\1\37\3\0\1"+
    "\17\1\34\1\14\1\1\1\15\1\24\1\23\1\1\1\21\1\1\1\5\1\40\1\16\1\22\1\11\1\20"+
    "\1\1\1\13\1\10\1\36\1\12\5\1\1\41\1\0\1\42\1\0\1\1\1\0\1\32\1\1\1\30\1\1\1"+
    "\25\1\6\4\1\1\5\2\1\1\27\1\31\1\4\1\1\1\26\1\1\1\33\4\1\1\35\1\1\145\0\12"+
    "\3\106\0\12\3\6\0\12\3\134\0\12\3\40\0\12\3\54\0\12\3\60\0\12\3\6\0\12\3\66"+
    "\0\12\3\26\0\12\3\74\0\12\3\16\0\62\3");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\2\1\4\6\2\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\13\2\1\16\6\2\1\17\1\20\4\2\1\21\5\2"+
    "\1\22\1\2\1\23\1\24\3\2\1\25";

  private static int [] zzUnpackAction() {
    int [] result = new int[60];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\234\0\303\0\352\0\u0111"+
    "\0\u0138\0\u015f\0\u0186\0\u01ad\0\u01d4\0\47\0\47\0\47"+
    "\0\47\0\47\0\47\0\47\0\116\0\116\0\u01fb\0\u0222"+
    "\0\u0249\0\u0270\0\u0297\0\u02be\0\u02e5\0\u030c\0\u0333\0\u035a"+
    "\0\u0381\0\116\0\u03a8\0\u03cf\0\u03f6\0\u041d\0\u0444\0\u046b"+
    "\0\116\0\116\0\u0492\0\u04b9\0\u04e0\0\u0507\0\116\0\u052e"+
    "\0\u0555\0\u057c\0\u05a3\0\u05ca\0\116\0\u05f1\0\116\0\u0618"+
    "\0\u063f\0\u0666\0\u068d\0\116";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[60];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\3\1\6\1\7\1\10"+
    "\2\3\1\11\1\12\1\3\1\13\1\3\1\5\1\3"+
    "\1\14\1\3\1\15\12\3\1\16\1\3\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\50\0\2\3\1\0\3\3"+
    "\1\0\27\3\1\0\1\3\10\0\2\4\44\0\2\3"+
    "\1\0\1\3\1\25\1\3\1\0\27\3\1\0\1\3"+
    "\7\0\2\3\1\0\1\3\1\26\1\3\1\0\27\3"+
    "\1\0\1\3\15\0\1\7\40\0\2\3\1\0\3\3"+
    "\1\0\1\3\1\27\25\3\1\0\1\3\7\0\2\3"+
    "\1\0\3\3\1\0\15\3\1\30\11\3\1\0\1\3"+
    "\7\0\2\3\1\0\3\3\1\0\21\3\1\31\5\3"+
    "\1\0\1\3\7\0\2\3\1\0\3\3\1\0\7\3"+
    "\1\32\17\3\1\0\1\3\7\0\2\3\1\0\3\3"+
    "\1\0\1\3\1\33\1\34\24\3\1\0\1\3\7\0"+
    "\2\3\1\0\1\3\1\26\1\3\1\0\3\3\1\35"+
    "\23\3\1\0\1\3\7\0\2\3\1\0\3\3\1\0"+
    "\2\3\1\36\24\3\1\0\1\3\7\0\2\3\1\0"+
    "\2\3\1\37\1\0\27\3\1\0\1\3\7\0\2\3"+
    "\1\0\3\3\1\0\17\3\1\40\7\3\1\0\1\3"+
    "\7\0\2\3\1\0\3\3\1\0\10\3\1\41\16\3"+
    "\1\0\1\3\7\0\2\3\1\0\3\3\1\0\26\3"+
    "\1\42\1\0\1\3\7\0\2\3\1\0\3\3\1\0"+
    "\27\3\1\0\1\43\7\0\2\3\1\0\3\3\1\0"+
    "\1\3\1\44\25\3\1\0\1\3\7\0\2\3\1\0"+
    "\3\3\1\0\3\3\1\45\23\3\1\0\1\3\7\0"+
    "\2\3\1\0\3\3\1\0\15\3\1\46\11\3\1\0"+
    "\1\3\7\0\2\3\1\0\3\3\1\0\20\3\1\47"+
    "\6\3\1\0\1\3\7\0\2\3\1\0\3\3\1\0"+
    "\10\3\1\50\16\3\1\0\1\3\7\0\2\3\1\0"+
    "\3\3\1\0\27\3\1\0\1\51\7\0\2\3\1\0"+
    "\3\3\1\0\6\3\1\52\20\3\1\0\1\3\7\0"+
    "\2\3\1\0\3\3\1\0\4\3\1\53\22\3\1\0"+
    "\1\3\7\0\2\3\1\0\3\3\1\0\16\3\1\54"+
    "\10\3\1\0\1\3\7\0\2\3\1\0\3\3\1\0"+
    "\22\3\1\55\4\3\1\0\1\3\7\0\2\3\1\0"+
    "\3\3\1\0\11\3\1\56\15\3\1\0\1\3\7\0"+
    "\2\3\1\0\3\3\1\0\5\3\1\57\21\3\1\0"+
    "\1\3\7\0\2\3\1\0\3\3\1\0\15\3\1\60"+
    "\11\3\1\0\1\3\7\0\2\3\1\0\3\3\1\0"+
    "\23\3\1\61\3\3\1\0\1\3\7\0\2\3\1\0"+
    "\3\3\1\0\12\3\1\62\14\3\1\0\1\3\7\0"+
    "\2\3\1\0\3\3\1\0\17\3\1\63\7\3\1\0"+
    "\1\3\7\0\2\3\1\0\3\3\1\0\24\3\1\64"+
    "\2\3\1\0\1\3\7\0\2\3\1\0\3\3\1\0"+
    "\13\3\1\65\13\3\1\0\1\3\7\0\2\3\1\0"+
    "\3\3\1\0\20\3\1\66\6\3\1\0\1\3\7\0"+
    "\2\3\1\0\3\3\1\0\25\3\1\67\1\3\1\0"+
    "\1\3\7\0\2\3\1\0\3\3\1\0\15\3\1\70"+
    "\11\3\1\0\1\3\7\0\2\3\1\0\3\3\1\0"+
    "\26\3\1\71\1\0\1\3\7\0\2\3\1\0\3\3"+
    "\1\0\25\3\1\72\1\3\1\0\1\3\7\0\2\3"+
    "\1\0\1\73\2\3\1\0\27\3\1\0\1\3\7\0"+
    "\2\3\1\0\3\3\1\0\15\3\1\74\11\3\1\0"+
    "\1\3\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1716];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\13\1\7\11\50\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[60];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MapperLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return BAD_CHARACTER;
            } 
            // fall through
          case 22: break;
          case 2: 
            { return ID;
            } 
            // fall through
          case 23: break;
          case 3: 
            { return NUM;
            } 
            // fall through
          case 24: break;
          case 4: 
            { return WHITE_SPACE;
            } 
            // fall through
          case 25: break;
          case 5: 
            { return EQUAL;
            } 
            // fall through
          case 26: break;
          case 6: 
            { return OPEN_SQUARE ;
            } 
            // fall through
          case 27: break;
          case 7: 
            { return CLOSE_SQUARE ;
            } 
            // fall through
          case 28: break;
          case 8: 
            { return OPEN_PARENTH ;
            } 
            // fall through
          case 29: break;
          case 9: 
            { return CLOSE_PARENTH ;
            } 
            // fall through
          case 30: break;
          case 10: 
            { return DOT ;
            } 
            // fall through
          case 31: break;
          case 11: 
            { return COMMA ;
            } 
            // fall through
          case 32: break;
          case 12: 
            { return PK;
            } 
            // fall through
          case 33: break;
          case 13: 
            { return FK;
            } 
            // fall through
          case 34: break;
          case 14: 
            { return NOT ;
            } 
            // fall through
          case 35: break;
          case 15: 
            { return NULL ;
            } 
            // fall through
          case 36: break;
          case 16: 
            { return FROM_WORD;
            } 
            // fall through
          case 37: break;
          case 17: 
            { return SOURCE_WORD;
            } 
            // fall through
          case 38: break;
          case 18: 
            { return MAPPING_WORD;
            } 
            // fall through
          case 39: break;
          case 19: 
            { return CONCAT_BY_WORD;
            } 
            // fall through
          case 40: break;
          case 20: 
            { return REFERENCE_WORD;
            } 
            // fall through
          case 41: break;
          case 21: 
            { return REFERENCE_TYPE_WORD;
            } 
            // fall through
          case 42: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
